services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - 5432:5432
    volumes:
      - survey-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - survey-net
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - survey-net
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - survey-net
volumes:
  survey-db:

networks:
  survey-net:
    name: survey-net